### ISSUE TITLE
Russian fronts

### ISSUE THREAD

**Issue by pvpshoot** [joker-119/Roth_UI#2]
Hi, russian fonts don't display corectly.
Can you add a fallback or change font with russian glyph?
![wowscrnshot_082816_114402](https://cloud.githubusercontent.com/assets/6636655/18032402/c5e0c0ca-6d14-11e6-8514-d714c3a80ae9.jpg)

**Comment by joker-119** [comment]
I will add a fallback, for now you can edit the fonts in Roth_UI/config.lua:703, Roth_UI/embeds/rTooltip/core.lua:20, Roth_UI/embeds/rInfostrings/config.lua:24 and Roth_UI/embeds/rChat/config.lua:18

Change "cfg.font = (mediapath.."ufont.com_devils-snare.ttf")" or "cfg.font = "Interface\AddOns\Roth_UI\media\ufont.com_devils-snare.ttf"" to "cfg.font = STANDARD_TEXT_FONT" to revert the font changes.

**Comment by joker-119** [comment]
As of latest version, there is still no check for localizations, however, all font configs have been moved to a single location here: 
https://github.com/galaxy119/Roth_UI/blob/master/config.lua#1015
changing this line from 
cfg.font = (mediapath.."Cracked-Narrow.ttf")
to
cfg.font = STANDARD_TEXT_FONT
will restore the default font to all aspects of the UI, you can use this if the font shipped with Roth UI doesn't work for your localization.
