### ISSUE TITLE
roth config

### ISSUE THREAD

**Issue by guojun12002** [joker-119/Roth_UI#9]
When I type in "roth config", it comes an error:

Message: Interface\AddOns\Roth_UI\core\slashcmd.lua:161: attempt to index field 'panel' (a nil value)
Time: 12/17/16 12:23:51
Count: 1
Stack: [C]: ?
Interface\AddOns\Roth_UI\core\slashcmd.lua:161: in function `?'
Interface\FrameXML\ChatFrame.lua:4385: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4053: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4089: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

How to fix it ?

**Comment by joker-119** [comment]
As reflected in patch notes, the GitHub version of Roth UI is now the alpha build for new features, please ensure you are using the version off wowinterface.com or curse
